// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkveguviszipwusssujj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrdmVndXZpc3ppcHd1c3NzdWpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0MTgxNzcsImV4cCI6MjA2Mjk5NDE3N30.Z64n4ljClGCDh2cCesZoG_ruacXUNTCbl5j3fXj6ORQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);